//Dec 30-2022-P2
package ExceptionHandling;

public class TryCatchPart2 {
	String name="Tom";
	public static void main(String[] args) {

		System.out.println("Hello Testing");
		
		TryCatchPart2 obj=new TryCatchPart2();
		System.out.println(obj.name);
		
		try {
		int i=9/0;
		}
		catch(ArithmeticException e) {
			System.out.println("some exception is coming");
			System.out.println(e.getMessage());
			
		}
	}

}
